### ISSUE TITLE
Client leaks memory over time

### ISSUE THREAD

**Issue by nivomi** [airbreather/Autopelago#98]
After about an hour of runtime, the memory usage of the Autopelago client climbs from ~220MB to ~380MB.

![image](https://github.com/user-attachments/assets/2475b9b5-6a1a-4148-827e-f3d12851b117)

It seems like a lot of this is coming from Avalonia resources: 
![image](https://github.com/user-attachments/assets/4fce2312-91e7-4844-9775-9f4875df5aaf)

I first noticed this after leaving the Rat gaming overnight (unhealthy for rats, I know) - the client reached over 2GB of memory consumption when I returned in the morning.

This leakage occurs whether the game is in a paused state or not.

**Comment by airbreather** [comment]
Possible references:
AvaloniaUI/Avalonia#3527
AvaloniaUI/Avalonia#5813
AvaloniaUI/Avalonia#5872

**Comment by airbreather** [comment]
An overnight run for me also shows seemingly unbounded memory growth, but it looks subtly different:
![image](https://github.com/user-attachments/assets/6bc80367-1b6b-447f-a724-86a8ed986c9c)

Mine ran on:
1. Linux
1. `main` as of f39e42e0
1. min/max = 12000 seconds (1 every 4/3 hours)

Comparing between the two, unmanaged memory seems to grow probably about as quickly in both, but the managed memory growth is much more pronounced in the first one posted on this the thread. I suspect that my very high min/max values are why I don't see the managed memory grow quite as much. Mine only would have seen about 26 game steps, so the effects of the issues that I linked in my previous comment are likely minimal in my run.

The unmanaged memory growth concerns me, because I don't know quite how to reliably debug it... but if I'm being pragmatic here, over the course of 8 hours, mine only grew by a factor of 65% (284 MiB added to a starting point of 435 MiB). If I could address the unbounded growth of managed memory, then I suppose I could live with this.

**Comment by airbreather** [comment]
I've pushed a series of changes that deal with the things I've seen in my own profiling:

1. The biggest offender in the original report has to do with the animated dashes showing the way to the rat's current target. I don't want to remove the animation or the dashes, but I **also** don't want to make people pay for them when the dashes aren't being drawn.
   - I've done a compromise: that memory will still (apparently, probably) grow without bound when the rat is displaying the path to its target, at the same rate as before, but **only** when the path is being displayed.
2. I'm pretty sure that the cause of seemingly unbounded unmanaged memory growth is due to the images that we flip back and forth. I'm not sure what of Avalonia's internals is causing this, but I've worked around it by just flipping `IsVisible` back and forth instead of the image sources themselves.
3. Related to the previous one, I've switched from using Avalonia.Svg.Skia to just Avalonia.Svg. I never measured the impact of this one specifically, but the idea is that the Skia version is creating images on-the-fly that might have the same problem, whereas the non-Skia version transforms the SVG path into Avalonia drawing context primitives, which is just an overall nicer design IMO and (importantly here) doesn't send unmanaged image data into Avalonia land where it might go into the same leaky spot that's responsible for the overall leak here.

I've also taken some preventative measures to address the concerns that I had linked earlier in the comments just in case, but it seems that I needed the combination of at least the first two items above in order to fully resolve this (to the best of my ability to tell).

Thanks for the report.

**Comment by nivomi** [comment]
The unmanaged memory _might_ be related to Skia's draw cache or something? But that should have an upper bound, I think?

I tried to do some research on this when I was profiling and stuff but I haven't worked with Skia/Avalonia so... Ran up against my limited experience real quick, lol

Thank you for taking a look at this! <3
